# Config
version: '2.29'

services:
  # PostGreSql
  postgres:
    image: bitnami/postgresql:latest
    container_name: database_pgsql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=project
      - POSTGRES_DB=pgsql
    volumes:
      - pgsql_data:/bitnami/postgresql

volumes:
  pgsql_data:
