# Config
version: '2.29'

services:
  #NextCloud
  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    environment:
      - POSTGRES_HOST=
      - POSTGRES_PASSWORD=project
      - POSTGRES_DB=pgsql
      - POSTGRES_USER=dev
      - PHP_MEMORY_LIMIT=10G
      - PHP_UPLOAD_LIMIT=10G
      - NEXTCLOUD_DATA_DIR=/var/www/html/nextcloud/data
    ports:
    - '81:81'
    - '444':'444'
    restart: always
    volumes:
      - ./nc_data:/var/www/html
    networks:
      - proxy

  # PostGreSql
  postgres:
    image: bitnami/postgresql:latest
    container_name: database_pgsql
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=project
      - POSTGRES_DB=pgsql
    networks:
      - proxy
    volumes:
      - ./pgsql_data:/bitnami/postgresql
      - ./pgsql_data:/opt/bitnami/postgresql/conf

volumes:
  pgsql_data:
  nc_data:

networks:
  proxy-tiex:
    external: true
    name: proxy
