# Config
version: '2.29'

services:
  #NextCloud
  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    environment:
      - POSTGRES_HOST=
      - POSTGRES_PASSWORD=project
      - POSTGRES_DB=pgsql
      - POSTGRES_USER=dev
      - PHP_MEMORY_LIMIT=10G
      - PHP_UPLOAD_LIMIT=10G
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nc_data:/var/www/html
    networks:
      - proxy

  # PostGreSql
  postgres:
    image: bitnami/postgresql:latest
    container_name: database_pgsql
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=project
      - POSTGRES_DB=pgsql
    networks:
      - proxy
    volumes:
      - ./pgsql_data:/bitnami/postgresql
      - ./pgsql_data:/opt/bitnami/postgresql/conf
    
  #Ngrok
  # ngrok:
  #   image: ngrok/ngrok:latest
  #   container_name: ngrok
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - 4040:4040

volumes:
  pgsql_data:
  nc_data:

networks:
  proxy:
    external:
      name: proxy
